baseurl = "https://adamknox.ca"
publishDir = ".."
languageCode = "en"
defaultContentLanguage = "en"
title = "Adam Knox"
theme = "dream"

# copyright = ""

googleAnalytics = "UA-148605526-1"

# disqusShortname = ""

enableRobotsTXT = true

paginate = 50

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  defaultDark = true
  backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  author = "Adam Knox"
  # description = ""
  avatar = "/img/adam_avatar.jpeg"
  headerTitle = "Adam Knox"
  motto = "Have a great day!"
  maxTags = 4
  # footerBottomText = ""

  # utterancesRepo = ""
  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "contact@adamknox.ca"
  linkedin      = "https://www.linkedin.com/in/adam-knox-4b86787b/"
  github        = "https://github.com/aspotic"
  stackoverflow = "https://stackoverflow.com/users/1679299/aspotic"
  instagram     = "https://www.instagram.com/aspotic/"
  youtube       = "https://www.youtube.com/channel/UC6ffMUc8CA1MJA3JTsU-ZbA"
  facebook      = "http://facebook.com/Adam.R.Knox"
  rss           = true
  # mastodon = ""
  # twitter = ""
  # codepen = ""

  siteStartYear = 2019

  favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true

  [params.advanced]
    customCSS = ["css/custom.css"]
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
[markup.goldmark.renderer]
  unsafe= true